ALTER TABLE channels
    ADD COLUMN IF NOT EXISTS color_set BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS color INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS color_background_emoji_id BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS profile_color_set BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS profile_color INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS profile_color_background_emoji_id BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS emoji_status_document_id BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS emoji_status_until INT NOT NULL DEFAULT 0;
