// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: langpack.sql

package sqlcgen

import (
	"context"
)

const getLangPackMeta = `-- name: GetLangPackMeta :one
SELECT lang_pack, lang_code, version, strings_count
FROM lang_packs
WHERE lang_pack = $1 AND lang_code = $2
`

type GetLangPackMetaParams struct {
	LangPack string
	LangCode string
}

type GetLangPackMetaRow struct {
	LangPack     string
	LangCode     string
	Version      int32
	StringsCount int32
}

func (q *Queries) GetLangPackMeta(ctx context.Context, arg GetLangPackMetaParams) (GetLangPackMetaRow, error) {
	row := q.db.QueryRow(ctx, getLangPackMeta, arg.LangPack, arg.LangCode)
	var i GetLangPackMetaRow
	err := row.Scan(
		&i.LangPack,
		&i.LangCode,
		&i.Version,
		&i.StringsCount,
	)
	return i, err
}

const getLangPackStringsByKeys = `-- name: GetLangPackStringsByKeys :many
SELECT
  lang_pack, lang_code, key, version, pluralized, value,
  zero_value, one_value, two_value, few_value, many_value, other_value, deleted
FROM lang_pack_strings
WHERE lang_pack = $1 AND lang_code = $2 AND key = ANY($3::text[]) AND NOT deleted
ORDER BY key
`

type GetLangPackStringsByKeysParams struct {
	LangPack string
	LangCode string
	Keys     []string
}

type GetLangPackStringsByKeysRow struct {
	LangPack   string
	LangCode   string
	Key        string
	Version    int32
	Pluralized bool
	Value      string
	ZeroValue  string
	OneValue   string
	TwoValue   string
	FewValue   string
	ManyValue  string
	OtherValue string
	Deleted    bool
}

func (q *Queries) GetLangPackStringsByKeys(ctx context.Context, arg GetLangPackStringsByKeysParams) ([]GetLangPackStringsByKeysRow, error) {
	rows, err := q.db.Query(ctx, getLangPackStringsByKeys, arg.LangPack, arg.LangCode, arg.Keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLangPackStringsByKeysRow
	for rows.Next() {
		var i GetLangPackStringsByKeysRow
		if err := rows.Scan(
			&i.LangPack,
			&i.LangCode,
			&i.Key,
			&i.Version,
			&i.Pluralized,
			&i.Value,
			&i.ZeroValue,
			&i.OneValue,
			&i.TwoValue,
			&i.FewValue,
			&i.ManyValue,
			&i.OtherValue,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLangPackStrings = `-- name: ListLangPackStrings :many
SELECT
  lang_pack, lang_code, key, version, pluralized, value,
  zero_value, one_value, two_value, few_value, many_value, other_value, deleted
FROM lang_pack_strings
WHERE lang_pack = $1 AND lang_code = $2 AND NOT deleted
ORDER BY key
`

type ListLangPackStringsParams struct {
	LangPack string
	LangCode string
}

type ListLangPackStringsRow struct {
	LangPack   string
	LangCode   string
	Key        string
	Version    int32
	Pluralized bool
	Value      string
	ZeroValue  string
	OneValue   string
	TwoValue   string
	FewValue   string
	ManyValue  string
	OtherValue string
	Deleted    bool
}

func (q *Queries) ListLangPackStrings(ctx context.Context, arg ListLangPackStringsParams) ([]ListLangPackStringsRow, error) {
	rows, err := q.db.Query(ctx, listLangPackStrings, arg.LangPack, arg.LangCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLangPackStringsRow
	for rows.Next() {
		var i ListLangPackStringsRow
		if err := rows.Scan(
			&i.LangPack,
			&i.LangCode,
			&i.Key,
			&i.Version,
			&i.Pluralized,
			&i.Value,
			&i.ZeroValue,
			&i.OneValue,
			&i.TwoValue,
			&i.FewValue,
			&i.ManyValue,
			&i.OtherValue,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLangPackMeta = `-- name: UpsertLangPackMeta :exec
INSERT INTO lang_packs (lang_pack, lang_code, version, strings_count)
VALUES ($1, $2, $3, $4)
ON CONFLICT (lang_pack, lang_code) DO UPDATE SET
  version = EXCLUDED.version,
  strings_count = EXCLUDED.strings_count,
  updated_at = now()
`

type UpsertLangPackMetaParams struct {
	LangPack     string
	LangCode     string
	Version      int32
	StringsCount int32
}

func (q *Queries) UpsertLangPackMeta(ctx context.Context, arg UpsertLangPackMetaParams) error {
	_, err := q.db.Exec(ctx, upsertLangPackMeta,
		arg.LangPack,
		arg.LangCode,
		arg.Version,
		arg.StringsCount,
	)
	return err
}

const upsertLangPackString = `-- name: UpsertLangPackString :exec
INSERT INTO lang_pack_strings (
  lang_pack, lang_code, key, version, pluralized, value,
  zero_value, one_value, two_value, few_value, many_value, other_value, deleted
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (lang_pack, lang_code, key) DO UPDATE SET
  version = EXCLUDED.version,
  pluralized = EXCLUDED.pluralized,
  value = EXCLUDED.value,
  zero_value = EXCLUDED.zero_value,
  one_value = EXCLUDED.one_value,
  two_value = EXCLUDED.two_value,
  few_value = EXCLUDED.few_value,
  many_value = EXCLUDED.many_value,
  other_value = EXCLUDED.other_value,
  deleted = EXCLUDED.deleted,
  updated_at = now()
`

type UpsertLangPackStringParams struct {
	LangPack   string
	LangCode   string
	Key        string
	Version    int32
	Pluralized bool
	Value      string
	ZeroValue  string
	OneValue   string
	TwoValue   string
	FewValue   string
	ManyValue  string
	OtherValue string
	Deleted    bool
}

func (q *Queries) UpsertLangPackString(ctx context.Context, arg UpsertLangPackStringParams) error {
	_, err := q.db.Exec(ctx, upsertLangPackString,
		arg.LangPack,
		arg.LangCode,
		arg.Key,
		arg.Version,
		arg.Pluralized,
		arg.Value,
		arg.ZeroValue,
		arg.OneValue,
		arg.TwoValue,
		arg.FewValue,
		arg.ManyValue,
		arg.OtherValue,
		arg.Deleted,
	)
	return err
}
