// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountPassword struct {
	UserID                  int64
	HasRecovery             bool
	HasSecureValues         bool
	HasPassword             bool
	Hint                    string
	EmailUnconfirmedPattern string
	LoginEmailPattern       string
	SecureRandom            []byte
	UpdatedAt               pgtype.Timestamptz
}

type AppConfig struct {
	Client     string
	Hash       int32
	ConfigJson []byte
	UpdatedAt  pgtype.Timestamptz
}

type AuthKey struct {
	AuthKeyID  int64
	Body       []byte
	ServerSalt int64
	CreatedAt  pgtype.Timestamptz
}

type Authorization struct {
	AuthKeyID     int64
	UserID        int64
	Hash          int64
	Layer         int32
	DeviceModel   string
	Platform      string
	SystemVersion string
	ApiID         int32
	AppVersion    string
	Ip            string
	CreatedAt     pgtype.Timestamptz
	ActiveAt      pgtype.Timestamptz
}

type AvailableReaction struct {
	Reaction            string
	Title               string
	Inactive            bool
	Premium             bool
	StaticIconID        int64
	AppearAnimationID   int64
	SelectAnimationID   int64
	ActivateAnimationID int64
	EffectAnimationID   int64
	AroundAnimationID   int64
	CenterIconID        int64
	SortOrder           int32
}

type Channel struct {
	ID                            int64
	AccessHash                    int64
	CreatorUserID                 int64
	Title                         string
	About                         string
	Username                      *string
	Broadcast                     bool
	Megagroup                     bool
	Forum                         bool
	ForumTabs                     bool
	Noforwards                    bool
	JoinToSend                    bool
	JoinRequest                   bool
	Signatures                    bool
	PreHistoryHidden              bool
	ParticipantsHidden            bool
	Antispam                      bool
	LinkedChatID                  int64
	SlowmodeSeconds               int32
	DefaultBannedRights           []byte
	AvailableReactions            []byte
	ColorSet                      bool
	Color                         int32
	ColorBackgroundEmojiID        int64
	ProfileColorSet               bool
	ProfileColor                  int32
	ProfileColorBackgroundEmojiID int64
	EmojiStatusDocumentID         int64
	EmojiStatusUntil              int32
	ParticipantsCount             int32
	AdminsCount                   int32
	KickedCount                   int32
	BannedCount                   int32
	TopMessageID                  int32
	Pts                           int32
	AdminLogSeq                   int64
	TtlPeriod                     int32
	Date                          int32
	Deleted                       bool
	CreatedAt                     pgtype.Timestamptz
	UpdatedAt                     pgtype.Timestamptz
	PinnedMessageID               int32
	Autotranslation               bool
	RestrictedSponsored           bool
	BroadcastMessagesAllowed      bool
	SendPaidMessagesStars         int64
	PhotoID                       int64
	PhotoDcID                     int32
	PhotoStripped                 []byte
}

type ChannelAdminLogEvent struct {
	ChannelID       int64
	ID              int64
	ActorUserID     int64
	EventDate       int32
	EventType       string
	PrevString      string
	NewString       string
	PrevBool        bool
	NewBool         bool
	PrevInt         int32
	NewInt          int32
	PrevParticipant []byte
	NewParticipant  []byte
	Participant     []byte
	Message         []byte
	PrevMessage     []byte
	NewMessage      []byte
	Query           string
	CreatedAt       pgtype.Timestamptz
}

type ChannelDialog struct {
	UserID                int64
	ChannelID             int64
	FolderID              int32
	TopMessageID          int32
	TopMessageDate        int32
	ReadInboxMaxID        int32
	ReadOutboxMaxID       int32
	UnreadCount           int32
	UnreadMentionsCount   int32
	UnreadReactionsCount  int32
	Pinned                bool
	PinnedOrder           int32
	UnreadMark            bool
	ViewForumAsMessages   bool
	NotifySettings        []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DefaultSendAsPeerType *string
	DefaultSendAsPeerID   *int64
}

type ChannelForumTopic struct {
	ChannelID            int64
	TopicID              int32
	CreatorUserID        int64
	Title                string
	IconColor            int32
	IconEmojiID          int64
	TitleMissing         bool
	Closed               bool
	Hidden               bool
	Pinned               bool
	PinnedOrder          int32
	Date                 int32
	TopMessageID         int32
	ReadInboxMaxID       int32
	ReadOutboxMaxID      int32
	UnreadCount          int32
	UnreadMentionsCount  int32
	UnreadReactionsCount int32
	UnreadPollVotesCount int32
	Deleted              bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type ChannelInvite struct {
	ChannelID      int64
	InviteID       int64
	Hash           string
	AdminUserID    int64
	Title          string
	Permanent      bool
	Revoked        bool
	RequestNeeded  bool
	ExpireDate     *int32
	UsageLimit     *int32
	UsageCount     int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	RequestedCount int32
}

type ChannelInviteHash struct {
	Hash      string
	ChannelID int64
	InviteID  int64
	UpdatedAt pgtype.Timestamptz
}

type ChannelInviteImporter struct {
	ChannelID   int64
	InviteID    int64
	UserID      int64
	Date        int32
	Requested   bool
	ApprovedBy  int64
	ViaChatlist bool
	About       string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ChannelMember struct {
	ChannelID            int64
	UserID               int64
	InviterUserID        int64
	Role                 string
	Status               string
	JoinedAt             int32
	LeftAt               int32
	AdminRights          []byte
	BannedRights         []byte
	Rank                 string
	AvailableMinID       int32
	AvailableMinPts      int32
	ReadInboxMaxID       int32
	ReadInboxDate        int32
	ReadOutboxMaxID      int32
	UnreadMark           bool
	SlowmodeLastSendDate int32
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type ChannelMessage struct {
	ChannelID           int64
	ID                  int32
	RandomID            int64
	SenderUserID        int64
	FromPeerType        string
	FromPeerID          int64
	SendAsPeerType      *string
	SendAsPeerID        *int64
	MessageDate         int32
	EditDate            int32
	Post                bool
	Silent              bool
	Noforwards          bool
	Body                string
	Entities            []byte
	ReplyTo             []byte
	ReplyToMsgID        int32
	ReplyToPeerType     string
	ReplyToPeerID       int64
	ReplyToTopID        int32
	FwdFrom             []byte
	DiscussionChannelID int64
	DiscussionMessageID int32
	Action              []byte
	Pts                 int32
	Deleted             bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ViewsCount          int32
	Media               []byte
}

type ChannelMessageReaction struct {
	ChannelID     int64
	MessageID     int32
	ReactedUserID int64
	SenderUserID  int64
	ReactionType  string
	ReactionValue string
	Big           bool
	Unread        bool
	ChosenOrder   int32
	ReactionDate  int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ChannelMessageViewer struct {
	ChannelID    int64
	MessageID    int32
	ViewerUserID int64
	ViewedAt     int32
	CreatedAt    pgtype.Timestamptz
}

type ChannelUnreadMention struct {
	UserID       int64
	ChannelID    int64
	MessageID    int32
	TopMessageID int32
	CreatedAt    pgtype.Timestamptz
}

type ChannelUpdateEvent struct {
	ChannelID    int64
	Pts          int32
	PtsCount     int32
	Date         int32
	EventType    string
	MessageID    int32
	MessageIds   []byte
	SenderUserID int64
	UserIds      []byte
	Payload      []byte
	CreatedAt    pgtype.Timestamptz
}

type ChannelUsername struct {
	UsernameLower string
	ChannelID     int64
	UpdatedAt     pgtype.Timestamptz
}

type Contact struct {
	UserID           int64
	ContactUserID    int64
	Mutual           bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ContactPhone     string
	ContactFirstName string
	ContactLastName  string
	Note             string
	NoteEntities     []byte
	CloseFriend      bool
	StoriesHidden    bool
}

type Country struct {
	Iso2        string
	DefaultName string
	Name        string
	Hidden      bool
	OrderIndex  int32
	UpdatedAt   pgtype.Timestamptz
}

type CountryCode struct {
	ID          int64
	Iso2        string
	CountryCode string
	Prefixes    []string
	Patterns    []string
	OrderIndex  int32
}

type Dialog struct {
	UserID                int64
	PeerType              string
	PeerID                int64
	TopMessageID          int32
	TopMessageDate        int32
	ReadInboxMaxID        int32
	ReadOutboxMaxID       int32
	UnreadCount           int32
	UnreadMentionsCount   int32
	UnreadReactionsCount  int32
	Pinned                bool
	UpdatedAt             pgtype.Timestamptz
	PinnedOrder           int32
	UnreadMark            bool
	HiddenPeerSettingsBar bool
	FolderID              int32
}

type DialogDraft struct {
	UserID       int64
	PeerType     string
	PeerID       int64
	TopMessageID int32
	Date         int32
	Draft        []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type DialogFilter struct {
	UserID     int64
	FilterID   int32
	IsChatlist bool
	Filter     []byte
	OrderValue int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type DialogFilterSetting struct {
	UserID      int64
	TagsEnabled bool
	UpdatedAt   pgtype.Timestamptz
}

type DispatchOutbox struct {
	ID               int64
	TargetUserID     int64
	Pts              int32
	EventType        string
	ExcludeSessionID int64
	Status           string
	Attempts         int32
	NextAttemptAt    pgtype.Timestamptz
	LastError        string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ExcludeAuthKeyID int64
}

type Document struct {
	ID            int64
	AccessHash    int64
	FileReference []byte
	Date          int32
	MimeType      string
	Size          int64
	DcID          int32
	Attributes    []byte
	Thumbs        []byte
	CreatedAt     pgtype.Timestamptz
}

type FileBlob struct {
	LocationKey string
	Backend     string
	ObjectKey   string
	Size        int64
	Sha256      []byte
	MimeType    string
	CreatedAt   pgtype.Timestamptz
}

type LangPack struct {
	LangPack     string
	LangCode     string
	Version      int32
	StringsCount int32
	UpdatedAt    pgtype.Timestamptz
}

type LangPackString struct {
	LangPack   string
	LangCode   string
	Key        string
	Version    int32
	Pluralized bool
	Value      string
	ZeroValue  string
	OneValue   string
	TwoValue   string
	FewValue   string
	ManyValue  string
	OtherValue string
	Deleted    bool
	UpdatedAt  pgtype.Timestamptz
}

type MessageBox struct {
	OwnerUserID      int64
	BoxID            int32
	PrivateMessageID int64
	MessageSenderID  int64
	PeerType         string
	PeerID           int64
	FromUserID       int64
	MessageDate      int32
	Outgoing         bool
	Body             string
	Entities         []byte
	Pts              int32
	Deleted          bool
	CreatedAt        pgtype.Timestamptz
	EditDate         int32
	Silent           bool
	Noforwards       bool
	ReplyToMsgID     int32
	ReplyToPeerType  string
	ReplyToPeerID    int64
	ReplyToTopID     int32
	QuoteText        string
	QuoteEntities    []byte
	QuoteOffset      int32
	FwdFromPeerType  string
	FwdFromPeerID    int64
	FwdFromName      string
	FwdDate          int32
	Media            []byte
}

type Photo struct {
	ID            int64
	AccessHash    int64
	FileReference []byte
	Date          int32
	DcID          int32
	HasStickers   bool
	Sizes         []byte
	CreatedAt     pgtype.Timestamptz
}

type PrivateMessage struct {
	ID              int64
	SenderUserID    int64
	RecipientUserID int64
	RandomID        int64
	MessageDate     int32
	Body            string
	Entities        []byte
	CreatedAt       pgtype.Timestamptz
	EditDate        int32
	Silent          bool
	Noforwards      bool
	ReplyToMsgID    int32
	ReplyToPeerType string
	ReplyToPeerID   int64
	ReplyToTopID    int32
	QuoteText       string
	QuoteEntities   []byte
	QuoteOffset     int32
	FwdFromPeerType string
	FwdFromPeerID   int64
	FwdFromName     string
	FwdDate         int32
	Media           []byte
}

type ProfilePhoto struct {
	OwnerPeerType string
	OwnerPeerID   int64
	PhotoID       int64
	Date          int32
	Active        bool
	SortOrder     int64
	CreatedAt     pgtype.Timestamptz
}

type StickerSet struct {
	ID              int64
	AccessHash      int64
	ShortName       string
	Title           string
	Count           int32
	Hash            int32
	SetKind         string
	Official        bool
	Animated        bool
	Videos          bool
	Emojis          bool
	Masks           bool
	Installed       bool
	Archived        bool
	InstalledDate   int32
	ThumbDocumentID int64
	Thumbs          []byte
	ThumbDcID       int32
	ThumbVersion    int32
	DocumentIds     []byte
	Packs           []byte
	SortOrder       int32
	SystemKey       string
	CreatedAt       pgtype.Timestamptz
}

type TempAuthKeyBinding struct {
	TempAuthKeyID    int64
	PermAuthKeyID    int64
	Nonce            int64
	ExpiresAt        int32
	EncryptedMessage []byte
	CreatedAt        pgtype.Timestamptz
	TempSessionID    int64
}

type UpdateState struct {
	AuthKeyID int64
	Pts       int32
	Qts       int32
	Date      int32
	Seq       int32
	UpdatedAt pgtype.Timestamptz
	UserID    int64
}

type UploadPart struct {
	OwnerUserID int64
	FileID      int64
	Part        int32
	TotalParts  int32
	IsBig       bool
	Bytes       []byte
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID          int64
	AccessHash  int64
	Phone       string
	FirstName   string
	LastName    string
	Username    string
	CountryCode string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Verified    bool
	Support     bool
	About       string
	LastSeenAt  int64
}

type UserRecentReaction struct {
	UserID        int64
	ReactionType  string
	ReactionValue string
	ReactionDate  int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type UserSavedReactionTag struct {
	UserID        int64
	ReactionType  string
	ReactionValue string
	Title         string
	ReactionCount int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type UserTopReaction struct {
	UserID        int64
	ReactionType  string
	ReactionValue string
	ReactionCount int32
	ReactionDate  int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type UserUpdateEvent struct {
	UserID           int64
	Pts              int32
	PtsCount         int32
	Date             int32
	EventType        string
	MessageBoxID     *int32
	PeerType         *string
	PeerID           *int64
	MaxID            int32
	StillUnreadCount int32
	CreatedAt        pgtype.Timestamptz
	EventBool        bool
	EventPeers       []byte
	PeerSettings     []byte
	MessageIds       []byte
	DialogFilter     []byte
	FilterOrder      []byte
	FolderPeers      []byte
	FilterID         int32
	TagsEnabled      bool
}

type UserUpdateWatermark struct {
	UserID        int64
	ContiguousPts int32
	UpdatedAt     pgtype.Timestamptz
}
